# Generated by Django 3.0.2 on 2020-04-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('busy', models.BooleanField()),
                ('busy_image', models.CharField(max_length=200)),
                ('not_busy_image', models.CharField(max_length=200)),
            ],
        ),
    ]
