# Generated by Django 3.0.5 on 2020-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gif_search_type',
            field=models.CharField(choices=[('RAW_URL', 'URL'), ('GIPHY_TRENDING_TERM', 'Giphy Trending Term')], default='RAW_URL', max_length=100),
        ),
    ]
